### ISSUE TITLE
Configure for local accesses

### ISSUE THREAD

**Issue by anhldbk** [emqtt/emq-auth-mongo#10]
@emqplus `emqtt` can be configured to allow a specific user to access locally.

For example: 

``` erlang
%% Allow clients from localhost to subscribe any topics
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
```

How we can achieve the same thing with this plugin?

**Comment by huangdan** [comment]
Can understand the clients.config model
