### ISSUE TITLE
mqttjs login emqtt using emq-auth-mongo

### ISSUE THREAD

**Issue by duchieu95** [emqtt/emq-auth-mongo#104]
I use the node js as API but mqtt login error encountered. bad username or password. password encryption
[bcrypt](https://www.npmjs.com/package/bcrypt-nodejs)

**Comment by HJianBo** [comment]
Hi, @duchieu95 The thread #78 may be helpful for you.

**Comment by emqplus** [comment]
@duchieu95 Close the issue.
