### ISSUE TITLE
does this plugin support salt with passwords

### ISSUE THREAD

**Issue by fouadkada** [emqtt/emq-auth-mongo#11]
is password salting supported?

**Comment by emqplus** [comment]
@fouadkada, no. I will upgrade the plugin later.

**Comment by fouadkada** [comment]
@emqplus thanks :)

**Comment by emqplus** [comment]
@fouadkada The password salting and pbkdf2 hash: https://github.com/emqtt/emq-auth-mongo/pull/45/files
