### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by reejinbouk** [emqtt/emq-auth-mongo#14]
Hello
can't connect to emqttd
i've created collections for ACL and Users, fill username and password hash, but still get this error:

22:45:32.727 [error] Client(mqtt-spy@127.0.0.1:39388): Username 'admin' login failed for {{badmatch,undefined},[{emqttd_auth_mongo,check,3,[{file,"src/emqttd_auth_mongo.erl"},{line,93}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,61}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,162}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,264}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

please advise how to fix? thank you

**Comment by akashtalole** [comment]
Same error for me.

**Comment by turtleDeng** [comment]
hi
  Try using the latest master branch
