### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by 112205997** [emqtt/emq-auth-mongo#23]
Could not connect: CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD
set in config：
auth.mongo.auth_query.password_hash = plain

mongodb：
{
  "_id" : ObjectId("5823e6d0567d5c3da0dcecfc"),
  "username" : "test",
  "password" : "test",
  "is_superuser" : false
}

does this plugin support “plain”？

**Comment by turtleDeng** [comment]
This problem, we #20  has been resolved, you update the latest code.

**Comment by 112205997** [comment]
OK
how can i download a success built plugin. I'm not familiar with Erlang

**Comment by turtleDeng** [comment]
http://emqtt.io/docs/v2/install.html#installing-from-source
