### ISSUE TITLE
Unable to connect to mongodb with --auth enabled

### ISSUE THREAD

**Issue by arihantdaga** [emqtt/emq-auth-mongo#24]
It works fine when i start mongodb without --auth param and in emq_auth_mongo.conf file leave auth.mongo.login and auth.mongo.password arguments commented. 
But when i uncomment these lines and use -
```
## Mongo User
auth.mongo.login = mqtt_admin

## Mongo Password
auth.mongo.password = 123456

## Mongo Database
auth.mongo.database = mqtt
```
i get this error - crashed with reason: <<"Can't pass authentification">> in mc_auth_logic:scram_sha_1_auth/5 line 41

While i have verified that my username and password are right. as i am able to connect to the database using mongo shell like this - 

`./bin/mongo localhost:21007/mqtt -username mqtt_admin -password 123456`

I think it is an issue with this plugin, please look into it..

**Comment by aliakbari** [comment]
for me too
 <<"Can't pass authentification">> in mc_auth_logic:scram_sha_1_auth/5 line 41

**Comment by emqplus** [comment]
@aliakbari @arihantdaga This issue is duplicated with https://github.com/emqtt/emq_auth_mongo/issues/23 if you use the release before 2.0-rc.3

**Comment by arihantdaga** [comment]
@emqplus  I think it's a different Issue. because that issue was with verifying mqtt clients with client username and password. That issue is fixed in the new version.
This issue is about connection between mongodb and this plugin. this plugin fails to connect to an authentication enabled mongodb, but connects very well without the authentication. 
I have built emqtt with latest source using these commands. 

```
git clone https://github.com/emqtt/emqttd-relx.git

cd emqttd-relx && make
```

And i am still having this problem.

**Comment by emqplus** [comment]
@turtleDeng please check the issue.

**Comment by ig0r** [comment]
guys, 

do you have any roadmap for implementing this?

Thanks!

**Comment by arihantdaga** [comment]
@ig0r . I think it's already fixed in the new release. Please pull latest and build again.

**Comment by ig0r** [comment]
@arihantdaga well, i see only this in the change logs:

```
emq-auth-mongo#31: cuttlefish:unset() if no ACL/super config exists
```

And it's a different [bug](https://github.com/emqtt/emq-auth-mongo/issues/31)

**Comment by ig0r** [comment]
@arihantdaga thanks, it seems you're right - it works for me with a simple setup. will check it more carefully.

**Comment by makoit** [comment]
Hey guys, I have the same problem:

`(****@1*****)1> 06:29:13.144 [error] CRASH REPORT Process <0.7819.0> with 0 neighbours crashed with reason: <<"Can't pass authentification">> in mc_auth_logic:scram_sha_1_auth/5 line 55`

With Robo 3T I have access with username and password to my mongodb. But If I try to connect the mongo plugin to mongodb I get the problem. 

Is there a solution?

**Comment by Gilbert-Wong** [comment]
Open a new issue and give us more details. For example, the emqx version you use, the erlang/otp version and your operating system. @makoit

**Comment by Gilbert-Wong** [comment]
@chipec84 Did you config the `etc/emqx_auth_mongo.conf` correctly? The issue has been closed and please use this [template](https://github.com/emqx/emqx/blob/emqx30/.github/ISSUE_TEMPLATE.md) to open a new issue.

**Comment by makoit** [comment]
@Gilbert-Wong I'm hosting the broker with docker in a azure container instance. For this I used the current version from the emq website. 

After long try and error it works. In the following picture you can see my config from the admin dashboard. 

![image](https://user-images.githubusercontent.com/42139290/47154162-d488a680-d2e1-11e8-866f-95dc193c24d8.png)

I only added the config with the white circle... Now it works,  BUT not really stable sometimes my mqtt client can connect and sometimes not. After the connection is successfully established the connection breaks off very often and the client can connect again after some time. I do not understand why.

Do you have a idea?

**Comment by Gilbert-Wong** [comment]
@makoit Sorry for late response. This issue has been closed, if you have any question, please open a new issue which help us discover your problem. This issue too old so I cannot understand what the `current version` you mean.

**Comment by eluchsinger** [comment]
@makoit  that worked. Don't know if it was the same issue, but I could get it working with that.
