### ISSUE TITLE
How to only use mongo auth user, and still use acl.conf ?

### ISSUE THREAD

**Issue by roytan883** [emqtt/emq-auth-mongo#28]
I just want mongo to only auth user when create connectioin. No need using mongo to ACL publish and subscription. 

The reason is that I want use my old mongodb tables to auth user login on emqtt, and make all user can't publish, only subscibe topic to receive PUSH message from backend server.

acl.conf works great for me (which i can specified only a few admin users can publish). But i tested when i use auth_mongo plugin, then acl.conf is invalid.

**Comment by roytan883** [comment]
Also i think in my case, using mongo to ACL is performance wasted. If there is 1M user, then need access 1M times, even has cache, but still waste lots of db performance at beginning.

acl.conf is good for my case:
```
{allow, {user, "229f03c94123b8f4e8f40aef4b9091061738c7e0"}, pubsub, ["#"]}.
{deny, all, publish, ["#"]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
{allow, all}.
```

**Comment by roytan883** [comment]
@emqplus any idea?

**Comment by huangdan** [comment]
if  you want mongo to only auth. No need using mongo to ACL publish and subscription. you can comments acl_query paragraphs in etc/emq_auth_mongo.conf
```
## auth_query
auth.mongo.auth_query.collection = mqtt_user

auth.mongo.auth_query.password_field = password

auth.mongo.auth_query.password_hash = sha256

auth.mongo.auth_query.selector = username=%u

## acl_query
##auth.mongo.acl_query = on

##auth.mongo.acl_query.collection = mqtt_acl

##auth.mongo.acl_query.selector = username=%u

```
