### ISSUE TITLE
Mongodb ACL Cannot work?

### ISSUE THREAD

**Issue by emqplus** [emqtt/emq-auth-mongo#31]
I am using mongodb auth plugin. here i am inserting records

db.mqtt_acl.insert({username: "test10", pubsub: ["t1"]})

db.mqtt_user.insert({username: "test10", password: "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"})

password is sha256 of '123'

i am getting connected successfully but can'r subscribe to topic:

[error] Client(122884296@127.0.0.1:44929): Cannot SUBSCRIBE [{<<"t1">>,[{qos,0}]}] for ACL Deny

**Comment by mkj-git** [comment]
any update on this issue?

**Comment by emqplus** [comment]
@mkj-git Fixed in PR: https://github.com/emqtt/emq-auth-mongo/pull/32
