### ISSUE TITLE
 login failed for {{badmap,undefined},[{maps,get,[<<"password">>,undefined,undefined]

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emq-auth-mongo#35]
I downloaded latest emqtt sever and installed mongodb plugin. My console is repeatedly filling with message

> 
> ' login failed for {{badmap,undefined},[{maps,get,[<<"password">>,undefined,undefined],[{file,"maps.erl"},{line,147}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,51}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,64}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,443}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,162}]},{emqttd_ws_client,handle_cast,2,[{file,"src/emqttd_ws_client.erl"},{line,112}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
> 
> 16:45:19.178 [error] Client(2ebdc358-9bdf-4e22-85b5-cf4dd7ba62e4@192.168.1.2:47112): Username '2ebdc358-9bdf-4e22-85b5-cf4dd7ba62e4' login failed for {{badmap,undefined},[{maps,get,[<<"password">>,undefined,undefined],[{file,"maps.erl"},{line,147}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,51}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,64}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,443}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,162}]},{emqttd_ws_client,handle_cast,2,[{file,"src/emqttd_ws_client.erl"},{line,112}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
> 
> 16:45:19.190 [error] Client(6b71b882-0cca-4999-b795-a967209dc422@192.168.1.2:47113): Username '6b71b882-0cca-4999-b795-a967209dc422' login failed for {{badmap,undefined},[{maps,get,[<<"password">>,undefined,undefined],[{file,"maps.erl"},{line,147}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,51}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,64}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,443}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,162}]},{emqttd_ws_client,handle_cast,2,[{file,"src/emqttd_ws_client.erl"},{line,112}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
> 

Mongodb doesn't have any user name '2ebdc358-9bdf-4e22-85b5-cf4dd7ba62e4'

I tried fresh i am getting

> 
> 17:14:26.564 [error] load plugin emq_auth_mongo error, cannot start app emq_auth_mongo for {bad_return,{{emq_auth_mongo_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_mongo,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},econnrefused}}}}}}}},[{emq_auth_mongo_app,start,2,[{file,"src/emq_auth_mongo_app.erl"},{line,35}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
> 17:14:26.564 [error] Supervisor {<0.1156.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_mongo, 1, emq_auth_mongo, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,27017},{database,"mqtt"}]) at undefined exit with reason econnrefused in context start_error
> 17:14:26.565 [error] Supervisor {<0.1154.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_mongo, emq_auth_mongo, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,27017},{database,"mqtt"}]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},econnrefused}} in context start_error
> 17:14:26.565 [error] Supervisor emq_auth_mongo_sup had child emq_auth_mongo started with ecpool:start_pool(emq_auth_mongo, emq_auth_mongo, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,27017},{database,"mqtt"}]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},econnrefused}}}} in context start_error
> 17:14:26.565 [error] CRASH REPORT Process <0.1151.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_mongo,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},econnrefused}}}}}}} in emq_auth_mongo_app:start/2 line 35 in application_master:init/4 line 134
> 17:14:28.525 [error] Client(6b71b882-0cca-4999-b795-a967209dc422@192.168.1.2:60907): Username '6b71b882-0cca-4999-b795-a967209dc422' login failed for "No auth module to check!"
> 17:14:36.876 [error] CRASH REPORT Process <0.1173.0> with 0 neighbours exited with reason: econnrefused in gen_server:init_it/6 line 344
> 17:14:36.877 [error] Supervisor {<0.1172.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_mongo, 1, emq_auth_mongo, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,27017},{database,"mqtt"}]) at undefined exit with reason econnrefused in context start_error
> 17:14:36.877 [error] Supervisor {<0.1170.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_mongo, emq_auth_mongo, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,27017},{database,"mqtt"}]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},econnrefused}} in context start_error
> 17:14:36.877 [error] load plugin emq_auth_mongo error, cannot start app emq_auth_mongo for {bad_return,{{emq_auth_mongo_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_mongo,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},econnrefused}}}}}}}},[{emq_auth_mongo_app,start,2,[{file,"src/emq_auth_mongo_app.erl"},{line,35}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
> 17:14:36.877 [error] Supervisor emq_auth_mongo_sup had child emq_auth_mongo started with ecpool:start_pool(emq_auth_mongo, emq_auth_mongo, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,27017},{database,"mqtt"}]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},econnrefused}}}} in context start_error
> 17:14:36.877 [error] CRASH REPORT Process <0.1167.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_mongo,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},econnrefused}}}}}}} in emq_auth_mongo_app:start/2 line 35 in application_master:init/4 line 134
> 17:14:48.913 [error] Client(122884296@127.0.0.1:56795): Username 'guest' login failed for "No auth module to check!"
> 17:14:48.920 [error] Client(122884296@127.0.0.1:56796): Username 'guest' login failed for "No auth module to check!"
> 

When loading mongodb i am getting

> 
> load plugin error: {emq_auth_mongo,
>                     {bad_return,
>                      {{emq_auth_mongo_app,start,[normal,[]]},
>                       {'EXIT',
>                        {{badmatch,
>                          {error,
>                           {shutdown,
>                            {failed_to_start_child,emq_auth_mongo,
>                             {shutdown,
>                              {failed_to_start_child,worker_sup,
>                               {shutdown,
>                                {failed_to_start_child,
>                                 {worker,1},
>                                 econnrefused}}}}}}}},
>                         [{emq_auth_mongo_app,start,2,
>                           [{file,"src/emq_auth_mongo_app.erl"},{line,35}]},
>                          {application_master,start_it_old,4,
>                           [{file,"application_master.erl"},{line,273}]}]}}}}}
>

**Comment by pavankumarkatakam** [comment]
Im getting this error how to solve
my logs

```
auth.mongo.server="mongodb://data:27017"
sed: bad option in substitution expression
listener.ssl.external.acceptors=32
node.max_ets_tables=2097152
node.process_limit=2097152
auth.mongo.auth_query.password_field="password"
listener.ws.external.acceptors=16
mqtt.allow_anonymous=false
node.name=690b3a079772@172.18.0.3
listener.tcp.external.max_clients=1000000
auth.mongo.database="mqtt"
auth.mongo.auth_query.password_hash="plain"
listener.ssl.external.max_clients=500000
auth.mongo.auth_query.collection="mqtt_user"
node.max_ports=1048576
listener.tcp.external.acceptors=64
log.console=console
listener.ws.external.max_clients=250000
mqtt.acl_nomatch=allow
EMQ_LOADED_PLUGINS="emq_auth_mongo,emq_recon,emq_modules,emq_retainer,emq_dashboard"
Node '690b3a079772@172.18.0.3' not responding to pings.
['2017-06-27T15:51:11Z']:waiting emqttd
Node '690b3a079772@172.18.0.3' not responding to pings.
Exec: /opt/emqttd/erts-8.1/bin/erlexec -noshell -noinput +Bd -boot /opt/emqttd/releases/2.2/emqttd -mode embedded -boot_var ERTS_LIB_DIR /opt/emqttd/erts-8.1/../lib -mnesia dir "/opt/emqttd/data/mnesia/690b3a079772@172.18.0.3" -config /opt/emqttd/data/configs/app.2017.06.27.15.51.11.config -args_file /opt/emqttd/data/configs/vm.2017.06.27.15.51.11.args -vm_args /opt/emqttd/data/configs/vm.2017.06.27.15.51.11.args -- foreground
Root: /opt/emqttd
starting emqttd on node '690b3a079772@172.18.0.3'
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
emqttd pubsub is starting...[ok]
emqttd stats is starting...[ok]
emqttd metrics is starting...[ok]
emqttd pooler is starting...[ok]
emqttd trace is starting...[ok]
emqttd client manager is starting...[ok]
emqttd session manager is starting...[ok]
emqttd session supervisor is starting...[ok]
emqttd wsclient supervisor is starting...[ok]
emqttd broker is starting...[ok]
emqttd alarm is starting...[ok]
emqttd mod supervisor is starting...[ok]
emqttd bridge supervisor is starting...[ok]
emqttd access control is starting...[ok]
emqttd system monitor is starting...[ok]
['2017-06-27T15:51:13Z']:waiting emqttd
Load emq_mod_presence module successfully.
Load emq_mod_subscription module successfully.
dashboard:http listen on 0.0.0.0:18083 with 2 acceptors.
mqtt:tcp listen on 127.0.0.1:11883 with 16 acceptors.
mqtt:tcp listen on 0.0.0.0:1883 with 64 acceptors.
mqtt:ws listen on 0.0.0.0:8083 with 16 acceptors.
mqtt:ssl listen on 0.0.0.0:8883 with 32 acceptors.
mqtt:wss listen on 0.0.0.0:8084 with 4 acceptors.
mqtt:api listen on 127.0.0.1:8080 with 4 acceptors.
emqttd 2.2 is running now
['2017-06-27T15:51:13Z']:emqttd start
['2017-06-27T15:51:13Z']:admin password changed to something
ok
15:52:28.001 [error] Client(C_1498578702935@172.18.0.1:36928): Username 'test' login failed for {{badmap,{error,timeout}},[{maps,get,[<<"\"password\"">>,{error,timeout},undefined],[{file,"maps.erl"},{line,192}]},{emq_auth_mongo,'-check/3-lc$^0/1-0-',2,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,513}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,194}]},{emqttd_ws_client,handle_cast,2,[{file,"src/emqttd_ws_client.erl"},{line,142}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]}]}
15:52:57.998 [error] Client(C_1498578702935@172.18.0.1:36950): Username 'test' login failed for {{badmap,{error,timeout}},[{maps,get,[<<"\"password\"">>,{error,timeout},undefined],[{file,"maps.erl"},{line,192}]},{emq_auth_mongo,'-check/3-lc$^0/1-0-',2,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,513}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,194}]},{emqttd_ws_client,handle_cast,2,[{file,"src/emqttd_ws_client.erl"},{line,142}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]}]}
```

**Comment by zhenwan** [comment]
I got the same error. So what is the solution here? Why was this issue closed without providing any solution?

**Comment by zhenwan** [comment]
What is the solution?

**Comment by zhenwan** [comment]
@terry-xiaoyu here is my emqtt_auth_mongo.conf

##--------------------------------------------------------------------
## MongoDB Auth/ACL Plugin
##--------------------------------------------------------------------

## MongoDB Topology Type.
##
## Value: single | unknown | sharded | rs
auth.mongo.type = single

## Sets the set name if type is rs.
##
## Value: String
## auth.mongo.rs_set_name =

## MongoDB server list.
##
## Value: String
##
## Examples: 127.0.0.1:27017,127.0.0.2:27017...
##auth.mongo.server = 127.0.0.1:27017
auth.mongo.server = <IP_ADRESS_IS_DELETED>:27017

## MongoDB pool size
##
## Value: Number
auth.mongo.pool = 8

## MongoDB login user.
##
## Value: String
## auth.mongo.login =

## MongoDB password.
##
## Value: String
## auth.mongo.password =

## MongoDB database
##
## Value: String
auth.mongo.database = mqtt

## MongoDB write mode.
##
## Value: unsafe | safe
## auth.mongo.w_mode =

## Mongo read mode.
##
## Value: master | slave_ok
## auth.mongo.r_mode =

## MongoDB topology options.
auth.mongo.topology.pool_size = 1
auth.mongo.topology.max_overflow = 0
## auth.mongo.topology.overflow_ttl = 1000
## auth.mongo.topology.overflow_check_period = 1000
## auth.mongo.topology.local_threshold_ms = 1000
## auth.mongo.topology.connect_timeout_ms = 20000
## auth.mongo.topology.socket_timeout_ms = 100
## auth.mongo.topology.server_selection_timeout_ms = 30000
## auth.mongo.topology.wait_queue_timeout_ms = 1000
## auth.mongo.topology.heartbeat_frequency_ms = 10000
## auth.mongo.topology.min_heartbeat_frequency_ms = 1000

## Authentication query.
auth.mongo.auth_query.collection = mqtt_user

## auth.mongo.auth_query.password_field = password

## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
## auth.mongo.auth_query.password_hash = bcrypt

## sha256 with salt suffix
## auth.mongo.auth_query.password_hash = sha256,salt

## sha256 with salt prefix
## auth.mongo.auth_query.password_hash = salt,sha256

## bcrypt with salt prefix
 auth.mongo.auth_query.password_hash = salt,bcrypt

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mongo.auth_query.password_hash = pbkdf2,sha256,1000,20

auth.mongo.auth_query.selector = username=%u

## Enable superuser query.
auth.mongo.super_query = on

auth.mongo.super_query.collection = mqtt_user

auth.mongo.super_query.super_field = is_superuser

auth.mongo.super_query.selector = username=%u

## Enable ACL query.
auth.mongo.acl_query = on

auth.mongo.acl_query.collection = mqtt_acl

auth.mongo.acl_query.selector = username=%u

==============================================================

The errors in the log:


================================================================
23:08:24.646 [error] Client(mqttjs_f19863aa@9.80.200.81:62570): Username 'testuser' login failed for {function_clause,[{emqttd_auth_mod,passwd_hash,[{salt,bcrypt},<<"testpassword">>],[{file,"src/emqttd_auth_mod.erl"},{line,55}]},{emq_auth_mongo,check_pass,3,[{file,"src/emq_auth_mongo.erl"},{line,65}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,54}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,540}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,214}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,324}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]}]}

**Comment by ghostec** [comment]
Any news on this?

**Comment by chipec84** [comment]
I have the exact same issue, anything new?
