### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Jackhjy** [emqtt/emq-auth-mongo#47]
I encountered that problem  and to be honest I still found it hard to get over it(Compiler emq-auth-mongo plug-in)

**This problem is:**
make[3]: rebar: Command not found
Makefile:13: recipe for target 'deps' failed
make[3]: *** [deps] Error 127
make[3]: Leaving directory '/home/emqtt/emq-auth-mongo/deps/goldrush'
../../erlang.mk:288: recipe for target 'deps' failed
make[2]: *** [deps] Error 2
make[2]: Leaving directory '/home/emqtt/emq-auth-mongo/deps/lager'
../../erlang.mk:288: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/emqtt/emq-auth-mongo/deps/emqttd'
erlang.mk:288: recipe for target 'deps' failed
make: *** [deps] Error 2

Thanks for give me help!

**Comment by huangdan** [comment]
Please install rebar:
```
sudo apt-get install rebar
or
sudo yum install rebar
````

**Comment by Jackhjy** [comment]
It's work!Thank you very much!

**Comment by Rjongenburger** [comment]
I can confirm
