### ISSUE TITLE
MOngodb username with dash (-) character is failing the authentication

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emq-auth-mongo#49]
I have this record

db.mqtt_user.insert({username: "a603d698-4017-4ff2-9161-8a48783d571b", password: "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3", is_superuser: false})

db.mqtt_acl.insert({username: "a603d698-4017-4ff2-9161-8a48783d571b", publish: ["user/msg/#", "user/status/%u"], subscribe: ["user/msg/%u", "user/status/#", "msghub/#"]})

if i remove `-` from username it works but username having `-` doesn't work and hence client authentication getting failed.

**Comment by huangdan** [comment]
@mkj-git The issue can't reproduce, please check your client side of the special character filter
