### ISSUE TITLE
Connecting to a replica set?

### ISSUE THREAD

**Issue by tercanfurkan** [emqtt/emq-auth-mongo#5]
Will it be possible to connect to a replica set using this plugin?

I can see that mongodb-erlang is being used as the mongodb driver. That driver allows replica set configuration. But, I think this plugin does not support replica sets at the moment. It doesn't seem to be possible to just pass a replica set in etc/plugin.config.

How much would it take to implement this?

Thanks!

**Comment by emqplus** [comment]
@tercanfurkan, we will enhance this plugin in 1.1 release.

**Comment by tercanfurkan** [comment]
Thanks @emqplus! Any estimates for the timetable?

**Comment by emqplus** [comment]
About one week later.
