### ISSUE TITLE
Paho java client failing to connect: Bad user name or password (4)

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emq-auth-mongo#52]
Mongo DB authentication: When i user username "test5" and password "123" from paho JS client it works but from java client it doesn't.
I have this code

> 
>         MqttConnectOptions conOpt = new MqttConnectOptions();
>         conOpt.setCleanSession(false);
>         conOpt.setUserName("test5");
>         conOpt.setPassword("123".toCharArray());
>         MqttDefaultFilePersistence filePersistence = new MqttDefaultFilePersistence("/home/manish/Downloads/mqttPersist");
>         client = new MqttAsyncClient(appProps.getProperty("mqtt.broker"),
>                 appProps.getProperty("mqtt.clientId"), filePersistence);
>         client.setCallback(this);
>         client.connect(conOpt, new IMqttActionListener() {
>             @Override
>             public void onSuccess(IMqttToken imt) {
>                 try {
>                     client.subscribe(Constants.INTERNAL_TOPICS, Constants.INTERNAL_TOPIC_QOS);
>                 } catch (MqttException ex) {
>                     ex.printStackTrace();
>                 }
>             }
> 
>             @Override
>             public void onFailure(IMqttToken imt, Throwable thrwbl) {
>                 thrwbl.printStackTrace();
>             }
>         });

i am getting this exception

> Bad user name or password (4)
> 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
> 	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:885)
> 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118)
> 	at java.lang.Thread.run(Thread.java:745)

emqt console

> 06:47:36.456 [error] Client(notification_subs_bot@127.0.0.1:50741): Username 'undefined' login failed for username_or_password_undefined
> 06:47:36.463 [error] Client(notification_subs_bot@127.0.0.1:50742): Username 'undefined' login failed for username_or_password_undefined

According paho documentation public void setPassword(char[] password) So here i am passing char[] as paasword

**Comment by mkj-git** [comment]
I can say this is a bug someone must fix this

**Comment by turtleDeng** [comment]
@mkj-git  Please check your password encryption type

**Comment by mkj-git** [comment]
Here is my ac.config
```

##--------------------------------------------------------------------
## MongoDB Auth/ACL Plugin
##--------------------------------------------------------------------

## Mongo Server 27017, 127.0.0.1:27017, localhost:27017
auth.mongo.server = 127.0.0.1:27017

## Mongo Pool Size
auth.mongo.pool = 8

## Mongo User
## auth.mongo.login = 

## Mongo Password
## auth.mongo.password = 

## Mongo Database
auth.mongo.database = mqtt

## auth_query
auth.mongo.auth_query.collection = mqtt_user

auth.mongo.auth_query.password_field = password

## Password hash: plain, md5, sha, sha256
auth.mongo.auth_query.password_hash = sha256

## sha256 with salt suffix
## auth.mongo.auth_query.password_hash = sha256 salt

## sha256 with salt suffix
## auth.mongo.auth_query.password_hash = salt sha256

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mongo.auth_query.password_hash = pbkdf2 sha256 1000 20

auth.mongo.auth_query.selector = username=%u

## super_query
auth.mongo.super_query = on

auth.mongo.super_query.collection = mqtt_user

auth.mongo.super_query.super_field = is_superuser

auth.mongo.super_query.selector = username=%u

## acl_query
auth.mongo.acl_query = on

auth.mongo.acl_query.collection = mqtt_acl

auth.mongo.acl_query.selector = username=%u

## acl_nomatch
auth.mongo.acl_nomatch = deny

```

**Comment by turtleDeng** [comment]
@mkj-git  auth.mongo.auth_query.password_hash = sha256

**Comment by mkj-git** [comment]
yes this is already there and even if i give sha256 equivalent of my password i got same error you can try with a java paho client

**Comment by mkj-git** [comment]
try with `a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3`

**Comment by turtleDeng** [comment]
@mkj-git client password plain, mongodb password is sha256

**Comment by mkj-git** [comment]
what i am saying i tried with both plain & sha256

`123`
`a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3`

in mongodb its `a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3`

**Comment by huangdan** [comment]
@mkj-git

> 
> 06:47:36.456 [error] Client(notification_subs_bot@127.0.0.1:50741): Username 'undefined' login failed for username_or_password_undefined
>06:47:36.463 [error] Client(notification_subs_bot@127.0.0.1:50742): Username 'undefined' login failed for username_or_password_undefined

 Check the value of username from Pahojs to EMQTT for undefined

**Comment by mkj-git** [comment]
In paho if i `setPassword("xyz")` then it is expected to send the password. are you saying that paho client is not sending username & password to the broker.

I too have seen 

`06:47:36.456 [error] Client(notification_subs_bot@127.0.0.1:50741): Username 'undefined' login failed for username_or_password_undefined`

and i was thinking that its broker bug

**Comment by mkj-git** [comment]
Can you confirm if client is not sending the credentials to broker or its broker issue. Because in either case its really a critical issue. I doubt anyone would be able to connect with paho client credntials

**Comment by tangblack** [comment]
@mkj-git

You call the wrong method to connect MQTT server.

Replace
`client.connect(conOpt, new IMqttActionListener() { // first parameter is Object not MqttConnectOptions, and it will create an empty MqttConnectOptions with empty user name and password.` 

to
`client.connect(conOpt, null, new IMqttActionListener() {`
