### ISSUE TITLE
Username 'dashboard' login failed for undefined

### ISSUE THREAD

**Issue by tercanfurkan** [emqtt/emq-auth-mongo#6]
Cannot configure the plugin and allow the dashboard user at the same time. What might I be missing?

Added the dashboard user to mongodb with the credentials: 
`{
    _id: ObjectId("5720ca7bbdc6a94896000006"),
    username: "dashboard",
    password: ""
}`
Then enabled the plugin. Other clients are able to login using other username/password pairs in the mqtt_user collection except the dashboard user.

I also tried changing the password of the dashboard user in the below file. Just not to use an empty password. Then ran "make". But the result was the same.
https://github.com/emqtt/emqttd_dashboard/blob/master/priv%2Fwww%2Fassets%2Fjs%2Fdashboard-custom.js#L450

**Comment by huangdan** [comment]
@tercanfurkan This issue has been fixed in 2.2-beta.3
