### ISSUE TITLE
How to set format of  MQTT message to store into Mongo

### ISSUE THREAD

**Issue by duythang** [emqtt/emq-auth-mongo#73]
Dear author

I want to store my MQTT messages from EMQTT to Mongo. 
I am confusing how can I set the format of these message before storing into Mongo.
For example, the format of message as a Json object I want to store is:
{ value: 10,
  topic: 'mqtt',
  qos: 0, }

Hope you have. Thank you so much.

**Comment by turtleDeng** [comment]
@duythang https://github.com/emqtt/emqttd/issues/1086
