### ISSUE TITLE
Password hash using pbkdf2

### ISSUE THREAD

**Issue by sobelman** [emqtt/emq-auth-mongo#83]
Hi, According to documentation the only options for password hash are: 
Password hash: plain, md5, sha, sha256, bcrypt
auth.mongo.auth_query.password_hash = sha256

Right now, all my users DB is hashed with pbkdf2 (x mosquitto user)
In short test i made, it failed to work with pbkdf2 when running the plugin with 
auth.mongo.auth_query.password_hash = pbkdf2

I can see it should be support with mysql db for example, 

Is this supposed to work ? not suppose to work?

Thanks.

**Comment by turtleDeng** [comment]
```
## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mongo.password_hash = pbkdf2,sha256,1000,20
```

**Comment by sobelman** [comment]
Thanks, 
Ok so i guess i got confused with the documentation because it wasn't in the main password hash option, 

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mongo.auth_query.password_hash = pbkdf2,sha256,1000,20

Any how, i tried to configure it with:
auth.mongo.auth_query.password_hash = pbkdf2

Should i just place the hash as is in the DB? or i should add something else? any pbkdf2 hash generator can be used for hashing?  for example: https://asecuritysite.com/encryption/PBKDF2z
for example: 
for password: 123456 i should have the hash look this in DB? D4E1EC18ED2307E7918AF1A837379CF2740A8D62EE1719C453BF70EC9C01C1F3
(sorry, i'm not an hash expert :) )
