### ISSUE TITLE
User CANNOT subscribe to a wild card while working with ACL 

### ISSUE THREAD

**Issue by sobelman** [emqtt/emq-auth-mongo#84]
Hi,
ACL in mongo DB looks like this:
{ "_id" : ObjectId("599957b16ad96915a0f5e3eb"), "username" : "iT0clFzAXM", "subscribe" : [ "device/v1/1234/#" ] }

When some super-user is publishing messages to:
device/v1/1234/test <payload> 

User iT0clFzAXM can see new messages only when subscribe to:
device/v1/1234/# <-New messages received 

When User iT0clFzAXM subscribe to '+' no message will be received & ACL error will display on the EMQ console: 
device/v1/+/# <-No new message 

12:40:34.493 [error] Client(bootstrap_tool@192.168.1.38:50120): Cannot SUBSCRIBE [{<<"device/v1/+/#">>,[{qos,0}]}] for ACL Deny

Is this the correct behavior? 
User cannot subscribe to wildcard and to get new messages for topics which he allow to be subscribe? 

Thanks

**Comment by turtleDeng** [comment]
@sobelman 
Here is correct, because you explicitly specified "device/v1/1234/#", not for device/v1/+/#.
