### ISSUE TITLE
Conf file attempted to set unknown variable: auth.mongo.acl_nomatch

### ISSUE THREAD

**Issue by vndn-developers** [emqtt/emq-auth-mongo#89]
I enable mongo authentication plugin and read mqtt_acl collection. After creating a rule, every topics are publish to all subscribers -  that means the acl has no effect.
I try to add auth.mongo.acl_nomatch but got the error
Please help me check this error !
"Conf file attempted to set unknown variable: auth.mongo.acl_nomatch"

**Comment by turtleDeng** [comment]
@vndn-developers 
auth.mongo.acl_nomatch unavailable,please use it emq.conf
```
mqtt.acl_nomatch = deny
```

**Comment by vndn-developers** [comment]
It seems that the mqtt_acl collection has no effect. 
After authenticating by username, password with mqtt_user collection, the subscriber still receives the topics published from anywhere. Even though the authentication username is not in mqtt_acl, this subscriber username still receive all topics.
Could you please help me check?
Thank you.

**Comment by vndn-developers** [comment]
Could you help, please?
I clone source code from the same git repository (http://emqtt.io/docs/v2/install.html#installing-from-source) but I encounter this issue on MAC OS only.
